export interface DefaultSubSpecies {
  id: string;
  name: string;
}

export interface DefaultSpecies {
  id: string;
  name: string;
  subspecies: DefaultSubSpecies[];
}

export interface DefaultMutation {
  id: string;
  name: string;
  inheritance: 'autosomal_recessive' | 'autosomal_dominant' | 'incomplete_dominant' | 'sex_linked_recessive';
}

export const defaultSpecies: DefaultSpecies[] = [
  {
    id: 'group_african',
    name: 'African Parrots',
    subspecies: [
      { id: 'african_brown_head', name: 'Brown-headed Parrot (P. cryptoxanthus)' },
      { id: 'african_cape_grey', name: 'Cape Parrot (P. robustus / grey-headed)' },
      { id: 'african_cape_g_fuscicollis', name: 'Grey-headed Parrot (P. fuscicollis suahelicus)' },
      { id: 'african_cape_b_fuscicollis', name: 'Brown-necked Parrot (P. f. fuscicollis)' },
      { id: 'african_grey_congo', name: 'Congo African Grey (Psittacus erithacus)' },
      { id: 'african_grey_timneh', name: 'Timneh African Grey (Psittacus timneh)' },
      { id: 'african_grey_principe', name: 'Principe African Grey' },
      { id: 'african_jardine_gulielmi', name: 'Jardine\'s Parrot (Congo - P. gulielmi gulielmi)' },
      { id: 'african_jardine_fantiensis', name: 'Jardine\'s Parrot (West African - P. g. fantiensis)' },
      { id: 'african_jardine_massaicus', name: 'Jardine\'s Parrot (Kenya - P. g. massaicus)' },
      { id: 'african_meyers_meyeri', name: 'Meyer\'s Parrot (P. meyeri meyeri)' },
      { id: 'african_meyers_damarensis', name: 'Meyer\'s Parrot (Damaraland - P. m. damarensis)' },
      { id: 'african_meyers_reichenowi', name: 'Meyer\'s Parrot (Reichenow\'s - P. m. reichenowi)' },
      { id: 'african_meyers_transvaalensis', name: 'Meyer\'s Parrot (Transvaal - P. m. transvaalensis)' },
      { id: 'african_meyers_matschiei', name: 'Meyer\'s Parrot (East African - P. m. matschiei)' },
      { id: 'african_meyers_neumanni', name: 'Meyer\'s Parrot (Angola - P. m. neumanni)' },
      { id: 'african_niam_niam', name: 'Niam-Niam Parrot (Poicephalus niamniamensis)' },
      { id: 'african_red_belly_rufiventris', name: 'Red-bellied Parrot (East African - P. r. rufiventris)' },
      { id: 'african_red_belly_pallidus', name: 'Red-bellied Parrot (Somali - P. r. pallidus)' },
      { id: 'african_rueppells', name: 'Rueppell\'s Parrot (Poicephalus rueppellii)' },
      { id: 'african_senegal_senegalus', name: 'Senegal Parrot (Yellow-vented - P. s. senegalus)' },
      { id: 'african_senegal_mesotypus', name: 'Senegal Parrot (Orange-vented - P. s. mesotypus)' },
      { id: 'african_senegal_versteri', name: 'Senegal Parrot (Red-vented - P. s. versteri)' },
      { id: 'african_yellow_fronted', name: 'Yellow-fronted Parrot (Poicephalus flavifrons)' },
      { id: 'african_greater_vasa', name: 'Greater Vasa Parrot (Coracopsis vasa)' },
      { id: 'african_lesser_vasa', name: 'Lesser Vasa Parrot (Coracopsis nigra)' },
      { id: 'african_seychelles_black', name: 'Seychelles Black Parrot (Coracopsis barklyi)' }
    ]
  },
  {
    id: 'group_amazons',
    name: 'Amazons',
    subspecies: [
      { id: 'amazon_black_billed', name: 'Black-billed Amazon' },
      { id: 'amazon_blue_front', name: 'Blue-fronted Amazon' },
      { id: 'amazon_blue_front_yellow_wing', name: 'Blue-fronted Amazon (Yellow-winged)' },
      { id: 'amazon_cuban', name: 'Cuban Amazon' },
      { id: 'amazon_double_yellow', name: 'Double Yellow-headed Amazon' },
      { id: 'amazon_double_yellow_tres', name: 'Double Yellow-headed (Tres Marias)' },
      { id: 'amazon_festive', name: 'Festive Amazon' },
      { id: 'amazon_green_cheeked', name: 'Green-cheeked (Red-crowned) Amazon' },
      { id: 'amazon_hispaniolan', name: 'Hispaniolan Amazon' },
      { id: 'amazon_imperial', name: 'Imperial Amazon (Sisserou)' },
      { id: 'amazon_lilac_crown', name: 'Lilac-crowned Amazon' },
      { id: 'amazon_lilac_crown_finsch', name: 'Lilac-crowned Amazon (Finsch\'s)' },
      { id: 'amazon_mealy', name: 'Mealy Amazon' },
      { id: 'amazon_orange_wing', name: 'Orange-winged Amazon' },
      { id: 'amazon_puerto_rican', name: 'Puerto Rican Amazon' },
      { id: 'amazon_red_browed', name: 'Red-browed Amazon' },
      { id: 'amazon_red_crowned', name: 'Red-crowned Amazon' },
      { id: 'amazon_red_lore', name: 'Red-lored Amazon' },
      { id: 'amazon_red_necked', name: 'Red-necked Amazon' },
      { id: 'amazon_red_spectacled', name: 'Red-spectacled Amazon' },
      { id: 'amazon_saint_lucia', name: 'Saint Lucia Amazon' },
      { id: 'amazon_saint_vincent', name: 'Saint Vincent Amazon' },
      { id: 'amazon_scaly_naped', name: 'Scaly-naped Amazon' },
      { id: 'amazon_tucuman', name: 'Tucuman Amazon' },
      { id: 'amazon_vinaceous', name: 'Vinaceous-breasted Amazon' },
      { id: 'amazon_white_front', name: 'White-fronted Amazon' },
      { id: 'amazon_yellow_billed', name: 'Yellow-billed Amazon' },
      { id: 'amazon_yellow_nape', name: 'Yellow-naped Amazon' },
      { id: 'amazon_yellow_shouldered', name: 'Yellow-shouldered Amazon' }
    ]
  },
  {
    id: 'group_cockatoos',
    name: 'Cockatoos',
    subspecies: [
      { id: 'cockatoo_bare_eye', name: 'Bare-eyed Cockatoo (Corella)' },
      { id: 'cockatoo_baudin_black', name: 'Baudin\'s Black Cockatoo' },
      { id: 'cockatoo_blue_eyed', name: 'Blue-eyed Cockatoo' },
      { id: 'cockatoo_carnaby_black', name: 'Carnaby\'s Black Cockatoo' },
      { id: 'cockatoo_sulphur_eleonora', name: 'Eleonora (Medium Sulphur-crested) Cockatoo' },
      { id: 'cockatoo_galah', name: 'Galah (Rose-breasted Cockatoo)' },
      { id: 'cockatoo_gang_gang', name: 'Gang-gang Cockatoo' },
      { id: 'cockatoo_glossy_black', name: 'Glossy Black Cockatoo' },
      { id: 'cockatoo_goffin', name: 'Goffin\'s Cockatoo' },
      { id: 'cockatoo_sulphur_greater', name: 'Greater Sulphur-crested Cockatoo' },
      { id: 'cockatoo_major_mitchell', name: 'Major Mitchell\'s Cockatoo' },
      { id: 'cockatoo_moluccan', name: 'Moluccan (Salmon-crested) Cockatoo' },
      { id: 'cockatoo_palm', name: 'Palm Cockatoo' },
      { id: 'cockatoo_red_tail_black', name: 'Red-tailed Black Cockatoo' },
      { id: 'cockatoo_red_vented', name: 'Red-vented (Philippine) Cockatoo' },
      { id: 'cockatoo_slender_corella', name: 'Slender-billed Corella' },
      { id: 'cockatoo_sulphur_triton', name: 'Triton Cockatoo' },
      { id: 'cockatoo_umbrella', name: 'Umbrella (White) Cockatoo' },
      { id: 'cockatoo_western_corella', name: 'Western Corella' },
      { id: 'cockatoo_yellow_tail_black', name: 'Yellow-tailed Black Cockatoo' }
    ]
  },
  {
    id: 'group_conures',
    name: 'Conures',
    subspecies: [
      { id: 'conure_austral', name: 'Austral Conure' },
      { id: 'conure_black_capped', name: 'Black-capped Conure (Pyrrhura rupicola)' },
      { id: 'conure_blue_crown', name: 'Blue-crowned Conure' },
      { id: 'conure_blue_throated', name: 'Blue-throated Conure (Pyrrhura cruentata)' },
      { id: 'conure_brown_throated', name: 'Brown-throated Conure' },
      { id: 'conure_crimson_belly', name: 'Crimson-bellied Conure (Pyrrhura perlata)' },
      { id: 'conure_demerara', name: 'Demerara Conure' },
      { id: 'conure_dusky', name: 'Dusky-headed Conure' },
      { id: 'conure_finschs', name: 'Finsch\'s Conure' },
      { id: 'conure_fiery_shouldered', name: 'Fiery-shouldered Conure' },
      { id: 'conure_gold_fronted', name: 'Gold-fronted Conure' },
      { id: 'conure_golden', name: 'Golden Conure (Queen of Bavaria)' },
      { id: 'conure_green_cheeked_only', name: 'Green-cheeked Conure' },
      { id: 'conure_grenada', name: 'Grenada Conure' },
      { id: 'conure_hoffmanns', name: 'Hoffmann\'s Conure' },
      { id: 'conure_jenday', name: 'Jenday Conure' },
      { id: 'conure_maroon_bellied', name: 'Maroon-bellied Conure' },
      { id: 'conure_maroon_tailed', name: 'Maroon-tailed Conure (Pyrrhura melanura)' },
      { id: 'conure_mitred', name: 'Mitred Conure' },
      { id: 'conure_nanday', name: 'Nanday Conure' },
      { id: 'conure_half_moon', name: 'Orange-fronted Conure (Half-moon)' },
      { id: 'conure_painted', name: 'Painted Conure' },
      { id: 'conure_patagonian', name: 'Patagonian Conure' },
      { id: 'conure_peach_front', name: 'Peach-fronted Conure' },
      { id: 'conure_pearly', name: 'Pearly Conure (Pyrrhura lepida)' },
      { id: 'conure_red_eared', name: 'Red-eared Conure' },
      { id: 'conure_cherry_headed', name: 'Red-masked Conure (Cherry-headed)' },
      { id: 'conure_rose_crowned', name: 'Rose-crowned Conure' },
      { id: 'conure_rose_fronted', name: 'Rose-fronted Conure' },
      { id: 'conure_santa_marta', name: 'Santa Marta Conure' },
      { id: 'conure_slender_billed', name: 'Slender-billed Conure' },
      { id: 'conure_sun', name: 'Sun Conure' },
      { id: 'conure_white_eared', name: 'White-eared Conure' },
      { id: 'conure_white_eyed', name: 'White-eyed Conure' },
      { id: 'conure_yellow_eared', name: 'Yellow-eared Conure' }
    ]
  },
  {
    id: 'group_fig_parrots',
    name: 'Fig Parrots',
    subspecies: [
      { id: 'fig_balanced', name: 'Balanced Fig Parrot' },
      { id: 'fig_blue_fronted', name: 'Blue-fronted Fig Parrot' },
      { id: 'fig_coxens', name: 'Coxen\'s Fig Parrot' },
      { id: 'fig_desmarests', name: 'Desmarest\'s Fig Parrot' },
      { id: 'fig_double_eyed', name: 'Double-eyed Fig Parrot' },
      { id: 'fig_edwardss', name: 'Edwards\'s Fig Parrot' },
      { id: 'fig_goldies', name: 'Goldie\'s Fig Parrot' },
      { id: 'fig_large', name: 'Large Fig Parrot' },
      { id: 'fig_marshalls', name: 'Marshall\'s Fig Parrot' },
      { id: 'fig_orange_breasted', name: 'Orange-breasted Fig Parrot' },
      { id: 'fig_red_browed', name: 'Red-browed Fig Parrot' },
      { id: 'fig_salvadoris', name: 'Salvadori\'s Fig Parrot' },
      { id: 'fig_sclaters', name: 'Sclater\'s Fig Parrot' },
      { id: 'fig_yellow_naped', name: 'Yellow-naped Fig Parrot' }
    ]
  },
  {
    id: 'group_finches',
    name: 'Doves and Finches',
    subspecies: [
      // Doves
      { id: 'dove_diamond', name: 'Diamond Dove (Geopelia cuneata)' },
      { id: 'dove_ringneck', name: 'Ringneck Dove (Streptopelia risoria)' },
      { id: 'dove_zebra', name: 'Zebra Dove (Geopelia striata)' },
      { id: 'dove_emerald', name: 'Emerald Dove (Chalcophaps indica)' },
      { id: 'dove_senegal', name: 'Senegal Dove (Spilopelia senegalensis)' },
      { id: 'dove_crested', name: 'Crested Pigeon (Ocyphaps lophotes)' },

      // Finches
      { id: 'finch_black_bellied_firefinch', name: 'Black-bellied Firefinch' },
      { id: 'finch_black_rumped_waxbill', name: 'Black-rumped Waxbill' },
      { id: 'finch_black_throated', name: 'Black-throated Finch (Parson Finch)' },
      { id: 'finch_blue_faced_parrot', name: 'Blue-faced Parrot Finch' },
      { id: 'finch_cordon_bleu_blue', name: 'Cordon-bleu (Blue-breasted)' },
      { id: 'finch_cordon_bleu_red', name: 'Cordon-bleu (Red-cheeked)' },
      { id: 'finch_cut_throat', name: 'Cut-throat Finch (Ribbon Finch)' },
      { id: 'finch_diamond_firetail', name: 'Diamond Firetail' },
      { id: 'finch_double_barred', name: 'Double-barred Finch (Owl Finch)' },
      { id: 'finch_forbes_parrot', name: 'Forbes\' Parrot Finch' },
      { id: 'finch_goldbreast_waxbill', name: 'Goldbreast Waxbill (Zebra Waxbill)' },
      { id: 'finch_gouldian_finch', name: 'Gouldian Finch' },
      { id: 'finch_green_winged_pytilia', name: 'Green-winged Pytilia (Melba Finch)' },
      { id: 'finch_java_sparrow', name: 'Java Sparrow' },
      { id: 'finch_lavender_waxbill', name: 'Lavender Waxbill' },
      { id: 'finch_long_tailed_shaft', name: 'Long-tailed Finch (Shaft-tail)' },
      { id: 'finch_masked', name: 'Masked Finch' },
      { id: 'finch_orange_cheeked_waxbill', name: 'Orange-cheeked Waxbill' },
      { id: 'finch_painted_emblema', name: 'Painted Finch (Emblema)' },
      { id: 'finch_pintailed_parrot', name: 'Pintailed Parrot Finch' },
      { id: 'finch_plum_headed', name: 'Plum-headed Finch' },
      { id: 'finch_red_billed_firefinch', name: 'Red-billed Firefinch' },
      { id: 'finch_red_eared_waxbill', name: 'Red-eared Waxbill (Common Waxbill)' },
      { id: 'finch_red_headed_aberdeen', name: 'Red-headed Finch (Aberdeen Finch)' },
      { id: 'finch_red_headed_parrot', name: 'Red-headed Parrot Finch' },
      { id: 'finch_seagreen_parrot', name: 'Seagreen Parrot Finch' },
      { id: 'finch_society_finch', name: 'Society Finch' },
      { id: 'finch_spice_munia', name: 'Spice Finch (Scaly-breasted Munia)' },
      { id: 'finch_star_finch', name: 'Star Finch' },
      { id: 'finch_strawberry_avadavat', name: 'Strawberry Finch (Red Avadavat)' },
      { id: 'finch_tricolored_munia', name: 'Tricolored Munia' },
      { id: 'finch_zebra_finch', name: 'Zebra Finch' }
    ]
  },
  {
    id: 'group_pheasants_quails',
    name: 'Pheasants and Quails',
    subspecies: [
      { id: 'quail_king', name: 'King Quail (Synoicus chinensis)' },
      { id: 'quail_japanese', name: 'Japanese Quail (Coturnix japonica)' },
      { id: 'quail_california', name: 'California Quail (Callipepla californica)' },
      { id: 'quail_bobwhite', name: 'Northern Bobwhite Quail (Colinus virginianus)' },
      { id: 'pheasant_ringnecked', name: 'Ring-necked Pheasant (Phasianus colchicus)' },
      { id: 'pheasant_golden', name: 'Golden Pheasant (Chrysolophus pictus)' },
      { id: 'pheasant_silver', name: 'Silver Pheasant (Lophura nycthemera)' },
      { id: 'pheasant_lady_amherst', name: 'Lady Amherst\'s Pheasant (Chrysolophus amherstiae)' }
    ]
  },
  {
    id: 'group_lories',
    name: 'Lories & Lorikeets',
    subspecies: [
      { id: 'lory_black', name: 'Black Lory' },
      { id: 'lory_brown', name: 'Brown Lory' },
      { id: 'lory_cardinal', name: 'Cardinal Lory' },
      { id: 'lory_chatting', name: 'Chatting Lory' },
      { id: 'lory_coconut_lorikeet', name: 'Coconut Lorikeet' },
      { id: 'lory_duchess_lorikeet', name: 'Duchess Lorikeet' },
      { id: 'lory_dusky', name: 'Dusky Lory' },
      { id: 'lory_emerald_lorikeet', name: 'Emerald Lorikeet' },
      { id: 'lory_fairy_lorikeet', name: 'Fairy Lorikeet' },
      { id: 'lory_goldies_lorikeet', name: 'Goldie\'s Lorikeet' },
      { id: 'lory_iris_lorikeet', name: 'Iris Lorikeet' },
      { id: 'lory_josephines_lorikeet', name: 'Josephine\'s Lorikeet' },
      { id: 'lory_kuhls_lorikeet', name: 'Kuhl\'s Lorikeet' },
      { id: 'lory_massena_rainbow_lorikeet', name: 'Massena\'s Rainbow Lorikeet' },
      { id: 'lory_meyers_lorikeet', name: 'Meyer\'s Lorikeet' },
      { id: 'lory_mindanao_lorikeet', name: 'Mindanao Lorikeet' },
      { id: 'lory_musk_lorikeet', name: 'Musk Lorikeet' },
      { id: 'lory_olive_headed_lorikeet', name: 'Olive-headed Lorikeet' },
      { id: 'lory_ornate_lorikeet', name: 'Ornate Lorikeet' },
      { id: 'lory_papuan_lorikeet', name: 'Papuan Lorikeet' },
      { id: 'lory_perfect_lorikeet', name: 'Perfect Lorikeet' },
      { id: 'lory_plum_faced_lorikeet', name: 'Plum-faced Lorikeet' },
      { id: 'lory_pohnpei_lorikeet', name: 'Pohnpei Lorikeet' },
      { id: 'lory_purple_bellied', name: 'Purple-bellied Lory' },
      { id: 'lory_purple_crowned_lorikeet', name: 'Purple-crowned Lorikeet' },
      { id: 'lory_rainbow_eastern', name: 'Rainbow Lorikeet (Eastern)' },
      { id: 'lory_rainbow_green_naped', name: 'Rainbow Lorikeet (Green-naped)' },
      { id: 'lory_rainbow_red_collared', name: 'Rainbow Lorikeet (Red-collared)' },
      { id: 'lory_red', name: 'Red Lory' },
      { id: 'lory_red_flanked_lorikeet', name: 'Red-flanked Lorikeet' },
      { id: 'lory_red_throated_lorikeet', name: 'Red-throated Lorikeet' },
      { id: 'lory_scaly_breasted_lorikeet', name: 'Scaly-breasted Lorikeet' },
      { id: 'lory_stellas_lorikeet', name: 'Stella\'s Lorikeet' },
      { id: 'lory_striated_lorikeet', name: 'Striated Lorikeet' },
      { id: 'lory_sunset_lorikeet', name: 'Sunset Lorikeet' },
      { id: 'lory_varied_lorikeet', name: 'Varied Lorikeet' },
      { id: 'lory_violet_necked', name: 'Violet-necked Lory' },
      { id: 'lory_whiskered_lorikeet', name: 'Whiskered Lorikeet' },
      { id: 'lory_yellow_billed_lorikeet', name: 'Yellow-billed Lorikeet' },
      { id: 'lory_yellow_streaked', name: 'Yellow-streaked Lory' }
    ]
  },
  {
    id: 'group_lovebirds',
    name: 'Lovebirds',
    subspecies: [
      { id: 'lovebird_abyssinian', name: 'Abyssinian (Black-winged) Lovebird' },
      { id: 'lovebird_peach_face_angolan', name: 'Angolan Peach-faced Lovebird' },
      { id: 'lovebird_black_cheek', name: 'Black-cheeked Lovebird' },
      { id: 'lovebird_black_collared', name: 'Black-collared Lovebird' },
      { id: 'lovebird_fischer', name: 'Fischer\'s Lovebird' },
      { id: 'lovebird_madagascar', name: 'Madagascar (Grey-headed) Lovebird' },
      { id: 'lovebird_masked', name: 'Masked (Yellow-collared) Lovebird' },
      { id: 'lovebird_nyasa', name: 'Nyasa (Lilian\'s) Lovebird' },
      { id: 'lovebird_peach_face', name: 'Peach-faced Lovebird' },
      { id: 'lovebird_red_faced', name: 'Red-faced Lovebird' }
    ]
  },
  {
    id: 'group_macaws',
    name: 'Macaws',
    subspecies: [
      { id: 'macaw_blue_gold', name: 'Blue-and-gold Macaw' },
      { id: 'macaw_blue_throated', name: 'Blue-throated Macaw' },
      { id: 'macaw_great_green', name: 'Buffon\'s (Great Green) Macaw' },
      { id: 'macaw_calico_hybrid', name: 'Calico Macaw (Hybrid)' },
      { id: 'macaw_camelot_hybrid', name: 'Camelot Macaw (Hybrid)' },
      { id: 'macaw_catalina', name: 'Catalina Macaw (Hybrid)' },
      { id: 'macaw_green_wing', name: 'Green-winged Macaw' },
      { id: 'macaw_hahns', name: 'Hahn\'s Macaw' },
      { id: 'macaw_harlequin', name: 'Harlequin Macaw (Hybrid)' },
      { id: 'macaw_hyacinth', name: 'Hyacinth Macaw' },
      { id: 'macaw_illiger', name: 'Illiger\'s Macaw' },
      { id: 'macaw_lears', name: 'Lear\'s Macaw' },
      { id: 'macaw_miligold_hybrid', name: 'Miligold Macaw (Hybrid)' },
      { id: 'macaw_military', name: 'Military Macaw' },
      { id: 'macaw_noble', name: 'Noble Macaw' },
      { id: 'macaw_red_bellied', name: 'Red-bellied Macaw' },
      { id: 'macaw_red_fronted', name: 'Red-fronted Macaw' },
      { id: 'macaw_scarlet_ca', name: 'Scarlet Macaw (Central American)' },
      { id: 'macaw_scarlet_sa', name: 'Scarlet Macaw (South American)' },
      { id: 'macaw_severe', name: 'Severe (Chestnut-fronted) Macaw' },
      { id: 'macaw_shamrock_hybrid', name: 'Sham-rock Macaw (Hybrid)' },
      { id: 'macaw_spix', name: 'Spix\'s Macaw' },
      { id: 'macaw_yellow_collared', name: 'Yellow-collared Macaw' }
    ]
  },
  {
    id: 'group_neotropical',
    name: 'Neotropical Parrots',
    subspecies: [
      { id: 'neo_caique_black_head', name: 'Black-headed Caique' },
      { id: 'neo_caique_white_belly', name: 'White-bellied Caique' },
      { id: 'neo_hawk_head', name: 'Hawk-headed (Red-fan) Parrot' },
      { id: 'neo_rusty_headed', name: 'Rusty-headed Parrot' },
      { id: 'neo_orange_bellied', name: 'Orange-bellied Parrot' },
      { id: 'neo_rock_parrot', name: 'Rock Parrot' },
      
      // Pionus Species & Subspecies
      { id: 'neo_pionus_blue_head_menstruus', name: 'Blue-headed Pionus (P. m. menstruus)' },
      { id: 'neo_pionus_blue_head_rubrigularis', name: 'Blue-headed Pionus (Reichenow\'s - P. m. rubrigularis)' },
      { id: 'neo_pionus_blue_head_reichenowi', name: 'Blue-headed Pionus (Southern - P. m. reichenowi)' },
      { id: 'neo_pionus_max_max', name: 'Maximilian\'s Pionus (P. m. maximiliani)' },
      { id: 'neo_pionus_max_siy', name: 'Maximilian\'s Pionus (Sclater\'s - P. m. siy)' },
      { id: 'neo_pionus_max_melanoblepharus', name: 'Maximilian\'s Pionus (Tucuman - P. m. melanoblepharus)' },
      { id: 'neo_pionus_bronze_chalcopterus', name: 'Bronze-winged Pionus (P. c. chalcopterus)' },
      { id: 'neo_pionus_bronze_cyanescens', name: 'Bronze-winged Pionus (Southern - P. c. cyanescens)' },
      { id: 'neo_pionus_dusky', name: 'Dusky Pionus (Pionus fuscus)' },
      { id: 'neo_pionus_coral_billed_sordidus', name: 'Coral-billed Pionus (P. s. sordidus)' },
      { id: 'neo_pionus_coral_billed_saturanus', name: 'Coral-billed Pionus (Sclater\'s - P. s. saturanus)' },
      { id: 'neo_pionus_coral_billed_ponsi', name: 'Coral-billed Pionus (Venezuelan - P. s. ponsi)' },
      { id: 'neo_pionus_coral_billed_corallinus', name: 'Coral-billed Pionus (Ecuador - P. s. corallinus)' },
      { id: 'neo_pionus_plum_crowned', name: 'Plum-crowned Pionus (Pionus tumultuosus)' },
      { id: 'neo_pionus_white_headed', name: 'White-headed Pionus (Pionus seniloides)' },
      { id: 'neo_pionus_white_cap', name: 'White-capped Pionus (Pionus senilis)' },

      // Parrotlet Species & Subspecies (Forpus & Touit)
      { id: 'neo_pacific_parrotlet', name: 'Pacific Parrotlet (Forpus coelestis)' },
      { id: 'neo_green_rumped_passerinus', name: 'Green-rumped Parrotlet (F. p. passerinus)' },
      { id: 'neo_green_rumped_viridissimus', name: 'Green-rumped Parrotlet (Venezuelan - F. p. viridissimus)' },
      { id: 'neo_green_rumped_cyanophanes', name: 'Green-rumped Parrotlet (Trinidad - F. p. cyanophanes)' },
      { id: 'neo_green_rumped_deliciosus', name: 'Green-rumped Parrotlet (Rio Branco - F. p. deliciosus)' },
      { id: 'neo_blue_winged_xanthopterygius', name: 'Blue-winged Parrotlet (F. x. xanthopterygius)' },
      { id: 'neo_blue_winged_flavescens', name: 'Blue-winged Parrotlet (Salvadori\'s - F. x. flavescens)' },
      { id: 'neo_mexican_cyanopygius', name: 'Mexican Parrotlet (Forpus cyanopygius)' },
      { id: 'neo_mexican_pallidus', name: 'Mexican Parrotlet (Sonora - F. c. pallidus)' },
      { id: 'neo_spectacled_conspicillatus', name: 'Spectacled Parrotlet (F. c. conspicillatus)' },
      { id: 'neo_spectacled_caucae', name: 'Spectacled Parrotlet (Cauca - F. c. caucae)' },
      { id: 'neo_spectacled_metae', name: 'Spectacled Parrotlet (Venezuelan - F. c. metae)' },
      { id: 'neo_turquoise_rumped_parrotlet', name: 'Turquoise-rumped Parrotlet (Forpus spengeli)' },
      { id: 'neo_yellow_faced_parrotlet', name: 'Yellow-faced Parrotlet (Forpus xanthops)' },
      { id: 'neo_lilac_tailed_parrotlet', name: 'Lilac-tailed Parrotlet (Touit batavicus)' },
      { id: 'neo_scarlet_shouldered_parrotlet', name: 'Scarlet-shouldered Parrotlet (Touit huetii)' },
      { id: 'neo_sapphire_rumped_parrotlet', name: 'Sapphire-rumped Parrotlet (Touit purpuratus)' },
      { id: 'neo_golden_tailed_parrotlet', name: 'Golden-tailed Parrotlet (Touit surdus)' },
      { id: 'neo_spot_winged_parrotlet', name: 'Spot-winged Parrotlet (Touit stictopterus)' },
      { id: 'neo_red_fronted_parrotlet', name: 'Red-fronted Parrotlet (Touit costaricensis)' },
      { id: 'neo_blue_fronted_parrotlet', name: 'Blue-fronted Parrotlet (Touit dilectissimus)' },
      { id: 'neo_brown_backed_parrotlet', name: 'Brown-backed Parrotlet (Touit melanonotus)' }
    ]
  },
  {
    id: 'group_parakeets',
    name: 'Parakeets',
    subspecies: [
      { id: 'parakeet_budgerigar', name: 'Budgerigar (Budgie - Melopsittacus undulatus)' },
      
      // Rosella Species & Subspecies (Platycercus)
      { id: 'parakeet_eastern_rosella', name: 'Eastern Rosella (Platycercus eximius)' },
      { id: 'parakeet_golden_mantled_rosella', name: 'Golden-mantled Rosella (P. e. cecilae)' },
      { id: 'parakeet_red_backed_eastern_rosella', name: 'Red-backed Eastern Rosella (P. e. eximius)' },
      { id: 'parakeet_crimson_rosella', name: 'Crimson Rosella (Platycercus elegans)' },
      { id: 'parakeet_yellow_rosella', name: 'Yellow Rosella (P. e. flaveolus)' },
      { id: 'parakeet_adelaide_rosella', name: 'Adelaide Rosella (P. e. adelaidae)' },
      { id: 'parakeet_western_rosella', name: 'Western Rosella / Stanley Rosella (Platycercus icterotis)' },
      { id: 'parakeet_red_backed_western_rosella', name: 'Red-backed Western Rosella (P. i. xanthogenys)' },
      { id: 'parakeet_pale_headed_rosella', name: 'Pale-headed Rosella (Platycercus adscitus)' },
      { id: 'parakeet_blue_cheeked_rosella', name: 'Blue-cheeked / Mealy Rosella (P. a. adscitus)' },
      { id: 'parakeet_green_rosella', name: 'Green Rosella / Tasmanian Rosella (Platycercus caledonicus)' },
      { id: 'parakeet_northern_rosella', name: 'Northern Rosella / Brown\'s Rosella (Platycercus venustus)' },

      // Ringnecks & Psittacula
      { id: 'parakeet_indian_ringneck', name: 'Indian Ringneck Parakeet (Psittacula krameri manillensis)' },
      { id: 'parakeet_african_ringneck', name: 'African Ringneck Parakeet (Psittacula krameri)' },
      { id: 'parakeet_alexandrine', name: 'Alexandrine Parakeet (Psittacula eupatria)' },
      { id: 'parakeet_nepalese_alexandrine', name: 'Nepalese Alexandrine Parakeet' },
      { id: 'parakeet_moustache', name: 'Moustache Parakeet (Psittacula alexandri)' },
      { id: 'parakeet_plum_head', name: 'Plum-headed Parakeet (Psittacula cyanocephala)' },
      { id: 'parakeet_blossom_headed', name: 'Blossom-headed Parakeet (Psittacula roseata)' },
      { id: 'parakeet_slaty_headed', name: 'Slaty-headed Parakeet (Psittacula himalayana)' },
      { id: 'parakeet_grey_headed', name: 'Grey-headed Parakeet (Psittacula finschii)' },
      { id: 'parakeet_derbyan', name: 'Derbyan Parakeet (Psittacula derbiana)' },
      { id: 'parakeet_malabar', name: 'Malabar Parakeet (Psittacula columboides)' },
      { id: 'parakeet_layards', name: 'Layard\'s Parakeet (Psittacula calthropae)' },
      { id: 'parakeet_newtons', name: 'Newton\'s Parakeet (Psittacula exsul)' },
      { id: 'parakeet_echo', name: 'Echo Parakeet (Psittacula eques)' },
      { id: 'parakeet_long_tailed', name: 'Long-tailed Parakeet (Psittacula longicauda)' },

      // Grass Parakeets (Neophema & Neopsephotus)
      { id: 'parakeet_bourkes', name: 'Bourke\'s Parakeet (Neopsephotus bourkii)' },
      { id: 'parakeet_scarlet_chested', name: 'Scarlet-chested Parakeet (Neophema splendida)' },
      { id: 'parakeet_turquoise', name: 'Turquoise Parakeet (Neophema pulchella)' },
      { id: 'parakeet_elegant', name: 'Elegant Parakeet (Neophema elegans)' },
      { id: 'parakeet_blue_winged', name: 'Blue-winged Parakeet (Neophema chrysostoma)' },

      // Psephotus & Allies
      { id: 'parakeet_red_rumped', name: 'Red-rumped Parakeet (Psephotus haematonotus)' },
      { id: 'parakeet_mulga', name: 'Mulga Parakeet (Psephotus varius)' },
      { id: 'parakeet_hooded', name: 'Hooded Parakeet (Psephotus dissimilis)' },
      { id: 'parakeet_golden_shouldered', name: 'Golden-shouldered Parakeet (Psephotus chrysopterygius)' },

      // King Parrots
      { id: 'parakeet_king_australian', name: 'King Parrot (Australian - Alisterus scapularis)' },
      { id: 'parakeet_king_amboina', name: 'King Parrot (Amboina - Alisterus amboinensis)' },
      { id: 'parakeet_king_green_wing', name: 'King Parrot (Green-winged - Alisterus chloropterus)' },

      // Kakarikis
      { id: 'parakeet_red_fronted_kakariki', name: 'Red-fronted Kakariki (Cyanoramphus novaezelandiae)' },
      { id: 'parakeet_yellow_fronted_kakariki', name: 'Yellow-fronted Kakariki (Cyanoramphus auriceps)' },

      // Ringneck & Barnardius Barnard
      { id: 'parakeet_port_lincoln', name: 'Port Lincoln Parakeet (Barnardius zonarius)' },
      { id: 'parakeet_twenty_eight', name: 'Twenty-eight Parakeet' },
      { id: 'parakeet_mallee_ringneck', name: 'Mallee Ringneck Parakeet' },
      { id: 'parakeet_cloncurry', name: 'Cloncurry Parakeet' },

      // Others
      { id: 'parakeet_princess_of_wales', name: 'Princess of Wales Parakeet (Polytelis alexandrae)' },
      { id: 'parakeet_regent_rock', name: 'Regent (Rock Pebbler) Parakeet (Polytelis anthopeplus)' },
      { id: 'parakeet_superb_barraband', name: 'Superb (Barraband) Parakeet (Polytelis swainsonii)' },
      { id: 'parakeet_swift', name: 'Swift Parakeet (Lathamus discolor)' },
      { id: 'parakeet_red_capped_parrot', name: 'Red-capped Parrot (Purpureicephalus spurius)' },
      { id: 'parakeet_quaker', name: 'Quaker (Monk) Parakeet (Myiopsitta monachus)' }
    ]
  },
  {
    id: 'group_toucans',
    name: 'Toucans',
    subspecies: [
      { id: 'toucan_black_mandibled', name: 'Black-mandibled Toucan' },
      { id: 'toucan_channel_billed', name: 'Channel-billed Toucan' },
      { id: 'toucan_chestnut_mandibled', name: 'Chestnut-mandibled Toucan' },
      { id: 'toucan_collared_aracari', name: 'Collared Aracari' },
      { id: 'toucan_crimson_rumped', name: 'Crimson-rumped Toucanet' },
      { id: 'toucan_curl_crested_aracari', name: 'Curl-crested Aracari' },
      { id: 'toucan_emerald', name: 'Emerald Toucanet (Blue-throated)' },
      { id: 'toucan_fiery_billed_aracari', name: 'Fiery-billed Aracari' },
      { id: 'toucan_green_aracari', name: 'Green Aracari' },
      { id: 'toucan_guyanan_toucanet', name: 'Guyanan Toucanet' },
      { id: 'toucan_keel_billed', name: 'Keel-billed Toucan' },
      { id: 'toucan_lettered_aracari', name: 'Lettered Aracari' },
      { id: 'toucan_many_banded_aracari', name: 'Many-banded Aracari' },
      { id: 'toucan_red_billed', name: 'Red-billed Toucan' },
      { id: 'toucan_saffron_toucanet', name: 'Saffron Toucanet' },
      { id: 'toucan_spot_billed_toucanet', name: 'Spot-billed Toucanet' },
      { id: 'toucan_toco', name: 'Toco Toucan' },
      { id: 'toucan_white_throated', name: 'White-throated Toucan' }
    ]
  }
];

export const defaultMutations: DefaultMutation[] = [
  { id: 'default_lutino', name: 'Lutino', inheritance: 'sex_linked_recessive' },
  { id: 'default_albino', name: 'Albino', inheritance: 'sex_linked_recessive' },
  { id: 'default_pallid', name: 'Pallid', inheritance: 'sex_linked_recessive' },
  { id: 'default_opaline', name: 'Opaline', inheritance: 'sex_linked_recessive' },
  { id: 'default_cinnamon', name: 'Cinnamon', inheritance: 'sex_linked_recessive' },
  { id: 'default_lacewing', name: 'Lacewing', inheritance: 'sex_linked_recessive' },
  { id: 'default_clearbody', name: 'Clearbody', inheritance: 'sex_linked_recessive' },
  { id: 'default_slate', name: 'Slate', inheritance: 'sex_linked_recessive' },
  { id: 'default_blue', name: 'Blue', inheritance: 'autosomal_recessive' },
  { id: 'default_aqua', name: 'Aqua', inheritance: 'autosomal_recessive' },
  { id: 'default_turquoise', name: 'Turquoise', inheritance: 'autosomal_recessive' },
  { id: 'default_fallow', name: 'Fallow', inheritance: 'autosomal_recessive' },
  { id: 'default_nsl_lutino', name: 'NSL Lutino (Non-Sex-Linked)', inheritance: 'autosomal_recessive' },
  { id: 'default_bronze_fallow', name: 'Bronze Fallow', inheritance: 'autosomal_recessive' },
  { id: 'default_pale_fallow', name: 'Pale Fallow', inheritance: 'autosomal_recessive' },
  { id: 'default_clearhead_fallow', name: 'Clearhead Fallow', inheritance: 'autosomal_recessive' },
  { id: 'default_dilute', name: 'Dilute', inheritance: 'autosomal_recessive' },
  { id: 'default_recessive_pied', name: 'Recessive Pied', inheritance: 'autosomal_recessive' },
  { id: 'default_grey_recessive', name: 'Grey (Recessive)', inheritance: 'autosomal_recessive' },
  { id: 'default_cleartail', name: 'Cleartail', inheritance: 'autosomal_recessive' },
  { id: 'default_buttercup', name: 'Buttercup', inheritance: 'autosomal_recessive' },
  { id: 'default_suffused', name: 'Suffused', inheritance: 'autosomal_recessive' },
  { id: 'default_dark_factor', name: 'Dark Factor', inheritance: 'incomplete_dominant' },
  { id: 'default_violet_factor', name: 'Violet Factor', inheritance: 'incomplete_dominant' },
  { id: 'default_misty', name: 'Misty Factor', inheritance: 'incomplete_dominant' },
  { id: 'default_spangle', name: 'Spangle', inheritance: 'incomplete_dominant' },
  { id: 'default_dominant_silver', name: 'Dominant Silver', inheritance: 'incomplete_dominant' },
  { id: 'default_pied', name: 'Dominant Pied', inheritance: 'autosomal_dominant' },
  { id: 'default_edged', name: 'Edged', inheritance: 'autosomal_dominant' },
  { id: 'default_dominant_grey', name: 'Dominant Grey', inheritance: 'autosomal_dominant' },
  { id: 'default_grizzle', name: 'Grizzle', inheritance: 'autosomal_dominant' },
  // User Requested and Finch/Quail/Dove Specific Mutations
  { id: 'default_melanistic', name: 'Melanistic', inheritance: 'autosomal_recessive' },
  { id: 'default_euwing', name: 'Euwing', inheritance: 'incomplete_dominant' },
  { id: 'default_fawn', name: 'Fawn', inheritance: 'sex_linked_recessive' },
  { id: 'default_black_cheeked', name: 'Black-cheeked', inheritance: 'autosomal_recessive' },
  { id: 'default_orange_breasted', name: 'Orange-breasted', inheritance: 'autosomal_recessive' },
  { id: 'default_penguin', name: 'Penguin', inheritance: 'autosomal_recessive' },
  { id: 'default_chestnut_flanked', name: 'Chestnut-flanked White (CFW)', inheritance: 'sex_linked_recessive' },
  { id: 'default_black_headed', name: 'Black Headed', inheritance: 'autosomal_recessive' },
  { id: 'default_yellow_headed', name: 'Yellow Headed', inheritance: 'sex_linked_recessive' },
  { id: 'default_white_breasted', name: 'White-breasted', inheritance: 'autosomal_recessive' },
  { id: 'default_emerald_mutation', name: 'Emerald', inheritance: 'autosomal_recessive' }
];
